--Pregunta 1

SELECT 
    LOCATIONS.LOCATION_ID, 
    COUNT(DEPARTMENTS.DEPARTMENT_ID) AS NUM_DEPARTAMENTS
FROM 
    LOCATIONS
JOIN 
    DEPARTMENTS 
ON 
    LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID
GROUP BY 
    LOCATIONS.LOCATION_ID;


--Pregunta 2 

SELECT 
    LOCATIONS.LOCATION_ID, 
    COUNT(DEPARTMENTS.DEPARTMENT_ID) AS NUM_DEPARTAMENTS
FROM 
    LOCATIONS
LEFT JOIN 
    DEPARTMENTS 
ON 
    LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID
GROUP BY 
    LOCATIONS.LOCATION_ID;

--Pregunta 3

SELECT 
    LOCATIONS.LOCATION_ID, 
    COUNT(DEPARTMENTS.DEPARTMENT_ID) AS NUM_DEPARTAMENTS
FROM 
    LOCATIONS
INNER JOIN 
    DEPARTMENTS 
ON 
    LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID
GROUP BY 
    LOCATIONS.LOCATION_ID
HAVING 
    COUNT(DEPARTMENTS.DEPARTMENT_ID) > 1;

--Pregunta 4

SELECT 
    DEPARTMENTS.DEPARTMENT_NAME, 
    COUNT(EMPLOYEES.EMPLOYEE_ID) AS NUM_EMPLOYEES, 
    SUM(EMPLOYEES.SALARY) AS TOTAL_SALARY, 
    AVG(EMPLOYEES.SALARY) AS AVG_SALARY
FROM 
    DEPARTMENTS
LEFT JOIN 
    EMPLOYEES 
ON 
    DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
GROUP BY 
    DEPARTMENTS.DEPARTMENT_NAME
ORDER BY 
    DEPARTMENTS.DEPARTMENT_NAME ASC, 
    AVG(EMPLOYEES.SALARY) DESC;


--Pregunta 5

SELECT 
    NVL(DEPARTMENTS.DEPARTMENT_NAME, 'No Department') AS DEPARTMENT_NAME,
    COUNT(EMPLOYEES.EMPLOYEE_ID) AS NUM_EMPLOYEES,
    SUM(EMPLOYEES.SALARY) AS TOTAL_SALARY,
    AVG(EMPLOYEES.SALARY) AS AVG_SALARY
FROM 
    EMPLOYEES
LEFT JOIN 
    DEPARTMENTS 
ON 
    EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
GROUP BY 
    DEPARTMENTS.DEPARTMENT_NAME
ORDER BY 
    DEPARTMENT_NAME ASC, 
    AVG_SALARY DESC;

